### PR TITLE
Better algorithm to display output, and PEP8

### PR DESCRIPTION
**Pull request by maethor**
Hi,

Thanks a lot for this plugin which save me a lot of time. I have cleaned a little the last algorithm that computes the state and returns the ouput. And I have make all the script PEP8 compatible.

I thought you could be interrested in merging these modifications. Do whatever you want with this PR :)

Thanks again.

### CODE REVIEW

**Comment by egeland** [comment]
Thanks for taking the time to improve this! :+1: 

Looks good - I'm not actively using this plugin at the moment, so I'll trust that you or others have tested/will test it.

:shipit:

**Comment by maethor** [comment]
In fact, I end up rewriting it more to manage multiple addresses and IPv6:

https://github.com/Sysnove/shinken-plugins/blob/master/check_rbl.py

With this version, when I  check a domain name, the script checks both it's IPv4 and it's IPv6. But this version depends on dnspython, so I will not make a pull request for it.

**Comment by egeland** [comment]
That version looks good, too - if you could make the IPv6 optional, I'd be happy to merge it in.
We (IT people) need to support IPv6 more.. :smile:

**Comment by egeland** [comment]
In case you have further updates, I've added you as a collaborator on this repo, so you can push any changes you feel are suitable. :)

**Comment by maethor** [comment]
Thank you :)

**Pull request merged**
